openapi: 3.0.3
info:
  title: HTTP RESTful API Device Management
  description:
    This is a RESTful API service intented to manage device metadata in a factory floor. The API specification has been
    implemented following OpenAPI 3.0 specification.

  version: 0.0.1

paths:
  /devices:
    get:
      tags:
        - devices
      summary: Lists existing devices
      description: Lists existing devices
      parameters:
        - name: name
          in: query
          description: Device name filter for query.
          required: false
          schema:
            type: string
        - name: type
          in: query
          description: Device type filter for query.
          required: false
          schema:
            type: string
            enum:
              - Sensor
              - Actuator
        - name: creationDateStart
          in: query
          description: Device creation date filter for query.
          required: false
          schema:
            type: integer
            format: int32
        - name: creationDateEnd
          in: query
          description: Device creation date filter for query.
          required: false
          schema:
            type: integer
            format: int32
        - name: locationId
          in: query
          description: Location identifier filter for query.
          required: false
          schema:
            type: integer
            format: uint32
        - name: locationName
          in: query
          description: Device location name filter for query.
          required: false
          schema:
            type: string
        - name: locationType
          in: query
          description: Location type filter for query.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/devices-get'
        '400':
          description: Invalid filter
        '404':
          description: Device not found

    post:
      tags:
        - devices
      summary: Creates or updates a device
      description: Creates or updates a device
      requestBody:
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/devices-post'
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid input

  /devices/{serialNumber}:
    get:
      tags:
        - devices
      summary: Finds device by ID
      description: Returns a single device
      parameters:
        - name: serialNumber
          in: path
          description: ID of device to return
          required: true
          schema:
            type: integer
            format: uint32
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/devices-get'
        '400':
          description: Invalid ID supplied
        '404':
          description: Device not found

    delete:
      tags:
        - devices
      summary: Deletes a device
      description: Deletes a device from the database
      parameters:
        - name: serialNumber
          in: path
          description: Serial Number of device to delete
          required: true
          schema:
            type: integer
            format: uint32
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: Device not found

  /devices/{serialNumber}/location:
    put:
      tags:
        - devices
      summary: Updates a device location in the database
      description: Updates a device location in the database
      parameters:
        - name: serialNumber
          in: path
          description: Serial Number of device to update
          required: true
          schema:
            type: integer
            format: uint32
      requestBody:
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/devices-put'
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: Device not found

  /locations:
    get:
      tags:
        - locations
      summary: Lists existing locations
      description: Lists existing locations
      parameters:
        - name: locationName
          in: query
          description: Location name filter for query.
          required: false
          schema:
            type: string
        - name: locationType
          in: query
          description: Location type filter for query.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/locations'
        '400':
          description: Invalid filter
        '404':
          description: Location not found

    post:
      tags:
        - locations
      summary: Creates or updates a location
      description: Creates or updates a location
      requestBody:
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/locations'
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid input

  /locations/{locationId}:
    get:
      tags:
        - locations
      summary: Finds location by ID
      description: Returns a single location
      parameters:
        - name: locationId
          in: path
          description: ID of location to return
          required: true
          schema:
            type: integer
            format: uint32
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/locations'
        '400':
          description: Invalid ID supplied
        '404':
          description: Location not found

    delete:
      tags:
        - locations
      summary: Deletes a location
      description: Deletes a location from the database
      parameters:
        - name: locationId
          in: path
          description: Location identifier to delete
          required: true
          schema:
            type: integer
            format: uint32
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: Location not found
        '412':
          description: Location has linked devices. Remove devices first or link them to another location

components:
  schemas:
    devices-put:
      required:
        - locationId
      type: object
      properties:
        locationId:
          type: integer
          format: uint32
          example: 12568
          description: Location identifier where device is placed

    devices-post:
      required:
        - serialNumber
        - name
        - type
      type: object
      properties:
        serialNumber:
          type: integer
          format: uint32
          example: 48356
          description: Serial Number of device
        name:
          type: string
          example: XLN3 Light Sensor
          description: Name of device
        type:
          type: string
          description: Type of device
          enum:
            - Sensor
            - Actuator
        locationId:
          type: integer
          format: uint32
          example: 12568
          description: Location identifier where device is placed

    devices-get:
      required:
        - serialNumber
        - name
        - type
        - creationDate
        - locationId
        - locationName
        - locationType
      type: object
      properties:
        serialNumber:
          type: integer
          format: uint32
          example: 48356
          description: Serial Number of device
        name:
          type: string
          example: XLN3 Light Sensor
          description: Name of device
        type:
          type: string
          description: Type of device
          enum:
            - Sensor
            - Actuator
        creationDate:
          type: string
          description: Date of device creation
          example: "2024-04-02 14:39:45"
        locationId:
          type: integer
          format: uint32
          example: 12568
          description: Location identifier where device is placed
        locationName:
          type: string
          example: Manufacturing building
          description: Name of location
        locationType:
          type: string
          description: Type of location
          enum:
            - Building
            - Room
            - Outdoor
            - Cargo Bay

    locations:
      required:
        - locationId
        - locationName
        - locationType
      type: object
      properties:
        locationId:
          type: integer
          format: uint32
          example: 12568
          description: Location identifier
        locationName:
          type: string
          example: Manufacturing building
          description: Name of location
        locationType:
          type: string
          description: Type of location
          enum:
            - Building
            - Room
            - Outdoor
            - Cargo Bay
