// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table devices {
  serial_number binary [primary key]
  device_name varchar
  device_type enum
  creation_date timestamp
}

Table locations {
  location_id binary [primary key]
  location_name varchar
  location_type enum
  device_count int
}

Table device_location {
  device_sn binary [primary key]
  location_id binary
}

Ref: devices.serial_number - device_location.device_sn // one-to-one

Ref: locations.location_id < device_location.location_id // one-to-many
